# Generated by Django 6.0.6 on 2026-06-20 10:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('identifier', models.CharField(max_length=254)),
                ('otp_hash', models.CharField(max_length=128)),
                ('otp_expires_at', models.DateTimeField()),
                ('otp_attempts', models.PositiveSmallIntegerField(default=0)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
