# Generated by Django 6.0.6 on 2026-07-01 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_add_password_reset_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='quidax_user_id',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
