# Generated by Django 6.0.6 on 2026-07-01 22:07

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoFeeSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap')], max_length=10, unique=True)),
                ('flat_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Crypto Fee Setting',
                'verbose_name_plural': 'Crypto Fee Settings',
            },
        ),
        migrations.CreateModel(
            name='CryptoOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap')], max_length=10)),
                ('coin', models.CharField(max_length=20)),
                ('to_coin', models.CharField(blank=True, max_length=20)),
                ('coin_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('to_coin_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('rate_ngn', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fee_ngn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('total_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='crypto_proofs/')),
                ('quidax_order_id', models.CharField(blank=True, max_length=100)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('payment_received', 'Payment Received'), ('waiting_deposit', 'Waiting for Deposit'), ('deposit_confirmed', 'Deposit Confirmed'), ('processing', 'Processing on Quidax'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='pending_payment', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoOrderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crypto.cryptoorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoQuote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quote_type', models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap')], max_length=10)),
                ('coin', models.CharField(max_length=20)),
                ('to_coin', models.CharField(blank=True, max_length=20)),
                ('coin_amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('rate_ngn', models.DecimalField(decimal_places=2, max_digits=20)),
                ('to_rate_ngn', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('fee_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('total_ngn', models.DecimalField(decimal_places=2, max_digits=14)),
                ('to_coin_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order', to='crypto.cryptoquote'),
        ),
        migrations.CreateModel(
            name='CryptoWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('available', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('reserved', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=24)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_wallets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CryptoDepositAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('quidax_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'coin'], name='crypto_cryp_user_id_d136e3_idx'), models.Index(fields=['address'], name='crypto_cryp_address_59c311_idx')],
                'unique_together': {('user', 'coin', 'network')},
            },
        ),
        migrations.AddIndex(
            model_name='cryptoquote',
            index=models.Index(fields=['user', '-created_at'], name='crypto_cryp_user_id_045fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoquote',
            index=models.Index(fields=['expires_at'], name='crypto_cryp_expires_3243bd_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['user', '-created_at'], name='crypto_cryp_user_id_b31120_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptoorder',
            index=models.Index(fields=['status'], name='crypto_cryp_status_7a6dc0_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowallet',
            index=models.Index(fields=['user', 'coin'], name='crypto_cryp_user_id_9e1939_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='cryptowallet',
            unique_together={('user', 'coin')},
        ),
    ]
