# Generated by Django 6.0.6 on 2026-07-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptoorder',
            name='flw_payment_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='cryptoorder',
            name='flw_transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
