# Generated by Django 6.0.6 on 2026-07-03 15:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0002_flw_payment_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptofeesettings',
            name='fee_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('sell', 'Sell'), ('swap', 'Swap'), ('withdraw', 'Withdraw')], max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='CryptoWithdrawal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coin', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=20)),
                ('fee', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=20)),
                ('quidax_withdrawal_id', models.CharField(blank=True, max_length=100)),
                ('tx_id', models.CharField(blank=True, max_length=200)),
                ('reference', models.CharField(blank=True, max_length=40, unique=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='processing', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CryptoWithdrawalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=60)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('withdrawal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='crypto.cryptowithdrawal')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cryptowithdrawal',
            index=models.Index(fields=['user', '-created_at'], name='crypto_cryp_user_id_b94a44_idx'),
        ),
        migrations.AddIndex(
            model_name='cryptowithdrawal',
            index=models.Index(fields=['status'], name='crypto_cryp_status_a34f0e_idx'),
        ),
    ]
