# Generated by Django 6.0.6 on 2026-10-06 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_alter_cryptofeesettings_fee_type_cryptowithdrawal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDeposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quidax_deposit_id', models.CharField(max_length=100, unique=True)),
                ('coin', models.CharField(max_length=20)),
                ('network', models.CharField(blank=True, max_length=30)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=24)),
                ('tx_id', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crypto_deposits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'coin'], name='crypto_cryp_user_id_cde5a6_idx')],
            },
        ),
    ]
